# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juangonzalez

# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-users

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    users_table_arn: /pragma/users_table_arn
    sns_topic_arn: /pragma/email_topic_arn
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: ${env:USERS_TABLE_ARN}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: ${env:SNS_TOPIC_ARN}
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: ${env:SSM_ARN}

  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${env:COGNITO_ISSUER_URL}
        audience:
          - ${env:COGNITO_AUDIENCE}

functions:
  hello:
    handler: src/lambdas/hello.handler
    events:
      - httpApi:
          path: /
          method: get
          authorizer:
            name: cognitoAuthorizer

  getUsers:
    handler: src/lambdas/getUsers.handler
    events:
      - httpApi:
          path: /users
          method: get

  getUser:
    handler: src/lambdas/getUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: get

  createUser:
    handler: src/lambdas/createUser.handler
    events:
      - httpApi:
          path: /users
          method: post

  deleteUser:
    handler: src/lambdas/deleteUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: delete

  updateUser:
    handler: src/lambdas/updateUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: put

  sendEmail:
    handler: src/lambdas/sendEmail.handler
    events:
      - httpApi:
          path: /send-email
          method: post
